### ISSUE TITLE
ModOrganizer doesn't open

### ISSUE THREAD

**Issue by Sztachu25** [Red007Master/Red-s-Guide-on-Installing-G.A.M.M.A.-on-Linux#4]
So basically, everything to the dot was working fine, I was going by  the tutorial, but when its time to open ModOrganizer via Bottles, it doesn't open and terminal shows this: 

18:03:35 (INFO) Launching an executable… 
18:03:35 (INFO) Using Steam runtime sniper 
18:03:35 (WARNING) Bottles runtime was requested but not found 
fsync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
008c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\winebth": c0000135
0024:err:module:import_dll Library Qt5WebEngineWidgets.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\46d5cdd2\\ModOrganizer.exe") not found
0024:err:module:import_dll Library Qt5WebSockets.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\46d5cdd2\\ModOrganizer.exe") not found
0024:err:module:import_dll Library uibase.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\46d5cdd2\\ModOrganizer.exe") not found
0024:err:module:import_dll Library archive.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\46d5cdd2\\ModOrganizer.exe") not found
0024:err:module:import_dll Library usvfs_x64.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\46d5cdd2\\ModOrganizer.exe") not found
0024:err:module:import_dll Library Qt5WebChannel.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\46d5cdd2\\ModOrganizer.exe") not found
0024:err:module:import_dll Library Qt5Widgets.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\46d5cdd2\\ModOrganizer.exe") not found
0024:err:module:import_dll Library Qt5Gui.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\46d5cdd2\\ModOrganizer.exe") not found
0024:err:module:import_dll Library Qt5Network.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\46d5cdd2\\ModOrganizer.exe") not found
0024:err:module:import_dll Library Qt5Core.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\46d5cdd2\\ModOrganizer.exe") not found
0024:err:module:import_dll Library liblz4.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\46d5cdd2\\ModOrganizer.exe") not found
0024:err:module:loader_init Importing dlls for L"Z:\\run\\user\\1000\\doc\\46d5cdd2\\ModOrganizer.exe" failed, status c0000135

Any clue what am I supposed to do? I'm on popOS as its my 1st time using linux and popos was working fine out of the box with my RTX 4070.

**Comment by Red007Master** [comment]
Do you have this files (Qt5WebEngineWidgets.dll/Qt5WebSockets.dll/Qt5WebChannel.dll/etc) in your installation (eg pathto/GAMMA/*)?

**Comment by LimonCaducado** [comment]
Ey man, first of all thanks for taking the time to make the guide, it was really useful.

Sadly I'm having the same issue described here. I'm on Nobara, and using the Flatpak permission manager I've made sure that Bottles has create/write/read permission on the whole system, but the mod manager is still not running. I get the following error message, similar to the OP with the difference that it is using EAC and BattlEye for me.

`21:17:42 (INFO) Using EasyAntiCheat runtime 
21:17:42 (INFO) Using BattlEye runtime 
fsync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
008c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\winebth": c0000135
0024:err:module:import_dll Library Qt5WebEngineWidgets.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\83f56bf4\\ModOrganizer.exe") not found
0024:err:module:import_dll Library Qt5WebSockets.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\83f56bf4\\ModOrganizer.exe") not found
0024:err:module:import_dll Library uibase.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\83f56bf4\\ModOrganizer.exe") not found
0024:err:module:import_dll Library archive.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\83f56bf4\\ModOrganizer.exe") not found
0024:err:module:import_dll Library usvfs_x64.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\83f56bf4\\ModOrganizer.exe") not found
0024:err:module:import_dll Library Qt5WebChannel.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\83f56bf4\\ModOrganizer.exe") not found
0024:err:module:import_dll Library Qt5Widgets.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\83f56bf4\\ModOrganizer.exe") not found
0024:err:module:import_dll Library Qt5Gui.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\83f56bf4\\ModOrganizer.exe") not found
0024:err:module:import_dll Library Qt5Network.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\83f56bf4\\ModOrganizer.exe") not found
0024:err:module:import_dll Library Qt5Core.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\83f56bf4\\ModOrganizer.exe") not found
0024:err:module:import_dll Library liblz4.dll (which is needed by L"Z:\\run\\user\\1000\\doc\\83f56bf4\\ModOrganizer.exe") not found
0024:err:module:loader_init Importing dlls for L"Z:\\run\\user\\1000\\doc\\83f56bf4\\ModOrganizer.exe" failed, status c0000135
`

Out of those; uibase and usvfs_x64 are present on the folder but the rest are missing. The only moment where I deviated from your video was telling Bottles to save the Bottle configuration on the same folder as where GAMMA was being installed for ease of finding, could that be it? Any idea how to solve it?

Thanks man.

**Comment by Red007Master** [comment]
> Ey man, first of all thanks for taking the time to make the guide, it was really useful.
> .....
> Thanks man.
> 
> EDIT: Solved. After checking around online someone mentioned that the Modmanager fails to check files properly if the Wineprefix is in the same folder as either Anomaly or Gamma. The why is unknown to me, some arcane reason lost deep within the circuits and binary, but moving the Bottle's prefix to the default location solved the problem in my case.

Interesting, glad to hear that it is solved.

And big thanks for mentioning how you fixed it!

**Comment by Red007Master** [comment]
New case: 
Deleting flatseal and re-adding shortcut helped.

**Comment by DDzwiedziu** [comment]
Did not delete Flat seal, but did 1.4 and worked for me.

…partially, because I've still get the error messages about the DLLs, but it runs.
